version: '3.8'

services:
  incanto-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: incanto-tea-store:latest
    container_name: incanto-tea-store
    ports:
      # Map container port 3000 to host port 8180
      - "8190:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    networks:
      - incanto-network

networks:
  incanto-network:
    driver: bridge
